export const THEMES = {
  dark: {
    key: "dark",
    name: "Dark",
    statusBar: "light",
    colors: {
      background: "#0B0C14",
      surface: "#161726",
      surfaceAlt: "#1D1E30",
      border: "#272939",
      textPrimary: "#F5F5FA",
      textSecondary: "#9C9DB5",
      textMuted: "#5C5E76",
      accent: "#8B7BFF",
      accentSoft: "#26224A",
      accentText: "#FFFFFF",
      danger: "#FF6B6B",
      tabBarBg: "#12131F",
      tabBarBorder: "#20212F",
    },
  },
  midnight: {
    key: "midnight",
    name: "Midnight",
    statusBar: "light",
    colors: {
      background: "#000000",
      surface: "#121212",
      surfaceAlt: "#1A1A1A",
      border: "#262626",
      textPrimary: "#FFFFFF",
      textSecondary: "#9A9A9A",
      textMuted: "#565656",
      accent: "#9D8CFF",
      accentSoft: "#231F3D",
      accentText: "#FFFFFF",
      danger: "#FF6B6B",
      tabBarBg: "#000000",
      tabBarBorder: "#1E1E1E",
    },
  },
  sunset: {
    key: "sunset",
    name: "Sunset",
    statusBar: "light",
    colors: {
      background: "#161014",
      surface: "#221A20",
      surfaceAlt: "#2A2027",
      border: "#3A2C33",
      textPrimary: "#FBF3F0",
      textSecondary: "#C3A9A5",
      textMuted: "#7A6165",
      accent: "#FF9770",
      accentSoft: "#3D2A22",
      accentText: "#1A1010",
      danger: "#FF6B6B",
      tabBarBg: "#1C1518",
      tabBarBorder: "#2E2226",
    },
  },
  light: {
    key: "light",
    name: "Light",
    statusBar: "dark",
    colors: {
      background: "#F7F7FB",
      surface: "#FFFFFF",
      surfaceAlt: "#F1F1F7",
      border: "#E7E7F0",
      textPrimary: "#17171F",
      textSecondary: "#6B6C80",
      textMuted: "#A3A4B8",
      accent: "#6C5CE7",
      accentSoft: "#EDEAFC",
      accentText: "#FFFFFF",
      danger: "#E5484D",
      tabBarBg: "#FFFFFF",
      tabBarBorder: "#ECECF3",
    },
  },
};

export const DEFAULT_THEME_KEY = "dark";
